print("i'm a beginner")
print("learning python")

# if you want to print both in same     line so:

print("i'm a beginner","learning python")

print(23)
print(34+43)


print("hello")    # interpreter tab tak code ko execute karta raha ga jab tak error nai aata or jab error aai ga kisi line par to vo ussi jagah ruk jaiga
print(hello)       # yaha par error iska bada program agli koi line par nai jaiga 

print("wait")